name: Upload setup-python  tool cache
on: push
jobs:
  upload_tool_cache:
    runs-on: ubuntu-20.04
    steps:
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"
      - name: Setup python 37
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.x
      - name: Setup python 38
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.x
      - name: Setup python 39
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.x
      - name: Setup python 310
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.x
      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf tool_cache.tar.gz *
      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{runner.tool_cache}}/tool_cache.tar.gz
